<a href="https://colab.research.google.com/github/ajayvallabh/Tensor_flow_Tutorial/blob/main/Tutorial2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import tensorflow as tf

In [4]:
# Initialization of Tensor
x= tf.constant(4.0)
print(x)

tf.Tensor(4.0, shape=(), dtype=float32)


In [7]:
x= tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [16]:
x = tf.constant([[1,2,3],[4,5,6]])

x = tf.ones((3,3))
x = tf.zeros((2,3))
x = tf.eye(3) # I for the identitiy matrix (eye)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [17]:
x = tf.random.normal((3,3), mean=0, stddev = 1)
print(x)

tf.Tensor(
[[ 1.1550151  -0.5418893  -0.8380504 ]
 [ 1.1236916   0.06380756  1.271775  ]
 [-0.21105115  1.327192   -0.71609193]], shape=(3, 3), dtype=float32)


In [18]:
x = tf.random.uniform((1,3), minval=0, maxval=1)
print(x)

tf.Tensor([[0.37243128 0.03926754 0.5377618 ]], shape=(1, 3), dtype=float32)


In [19]:
x =tf.range(9)

In [21]:
x = tf.range(start=1, limit=10, delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [23]:
x = tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float32)


In [33]:
# Mathematical Operations
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x, y)
z =x + y
z = tf.subtract(x, y)
z =x-y
print(z)

z =tf.divide(x, y)
print(z)


tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [34]:
z =tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [36]:
z = tf.reduce_sum(x*y, axis=0)

z = x**5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [45]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
print(z)

tf.Tensor(
[[1.2975384  1.0476406  1.8536456  0.20450845]
 [2.520816   2.1294541  4.2918177  1.101762  ]], shape=(2, 4), dtype=float32)


In [50]:
# Indexing
x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [52]:
indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)

print(x)

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [55]:
x =tf.constant([[1,2],
               [3,4],
               [5,6]])
print(x[0,:])
print(x[0:2,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [57]:
# Reshaping
x =tf.range(9)
print(x)

x = tf.reshape(x, (3,3))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [59]:
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
